In [4]:
from deap import base, creator, tools, algorithms
import random
import numpy as np

In [2]:
# Problem parameters
N = 3000  # Number of projects
M = 125   # Number of experts
K = 5     # Number of experts per project
pop_size = 100


In [1]:
class GA_MATRIX:
    def __init__(self, population_size:int, M:int, N:int, generations:int, crossover_rate:float, mutation_rate:float, 
                fitness_function:function) -> None:
        '''
        '''
        self.population_size = population_size
        self.M = M
        self.N = N
        self.generations = generations
        self.crossover_rate = crossover_rate
        self.mutation_rate = mutation_rate
        self.fitness_function = fitness_function
        self.population = []


    def initialize_population(self, K):
        '''
        初始化种群
        '''
        for _ in range(self.population_size):
            # 每个个体是一个 M x N 的矩阵
            individual = np.zeros((self.M, self.N), dtype=int)
            for j in range(self.N):
                experts = np.random.choice(M, K, replace=False)
                individual[experts, j] = 1
            self.population.append(individual.reshape(1,self.M * self.N))
        self.population = np.vstack(self.population)

    def select(self):
        ''' 
        轮盘赌
        '''
        fitness = self.fitness_function(self.population)
        probabilities = fitness / fitness.sum()
        indices = np.random.choice(np.arange(self.population_size), 
                                   size=self.population_size,
                                   replace=True,
                                   p=probabilities)
        return self.population[indices]
    
    # 交叉操作：单点交叉
    def crossover(self, parent1, parent2):
        point = np.random.randint(self.N-1)
        child1 = np.hstack((parent1[:, :point], parent2[:, point:]))
        child2 = np.hstack((parent2[:, :point], parent1[:, point:]))
        return child1, child2

    # 变异操作
    def mutate(individual):
        for j in range(num_papers):
            if np.random.rand() < mutation_rate:
                experts = np.random.choice(num_experts, papers_per_expert, replace=False)
                individual[:, j] = 0
                individual[experts, j] = 1
        return individual

    



SyntaxError: expected argument value expression (1278095524.py, line 34)

In [7]:
array = np.array([[1, 2],
                  [4, 6],
                  [7, 9]])
print(array.shape)

array[2,1]


(3, 2)


np.int64(9)

In [5]:
# 选择操作：轮盘赌选择
def select(population, fitness_scores):
    probs = fitness_scores / np.sum(fitness_scores)
    indices = np.random.choice(len(population), size=pop_size, p=probs)
    return population[indices]

In [8]:
def calculate_I_ij(S, i, j):
    """
    计算专家对 (i, j) 的交集模。
    """
    expert_i = S[i, :]
    expert_j = S[j, :]

    # 计算两者的交集模，即向量的内积
    I_ij = np.dot(expert_i, expert_j)

    return I_ij

In [16]:
def evaluate(individual):
    """
    评估函数
    1.最大化所有作品的专家组的交集模
    2.最小化交集模之间的偏差
    """

    # 转换个体为矩阵 S
    S = np.array(individual).reshape((M, N))  
    print(S)

    # 第一个目标
    fit_1 = 0
    for p in range(N):
        experts_for_p = np.where(S[:,p] == 1)[0]
        expert_matrix_p = S[experts_for_p, :]
        num_experts = expert_matrix_p.shape[0]
        for i in range(num_experts):
            for j in range(i+1, num_experts):
                I_ij = calculate_I_ij(expert_matrix_p, i, j)
                fit_1 += I_ij

    # 第二个目标
    fit_2 = 0
    for i in range(M):
        for j in range(i+1, M):
            fit_2 += (calculate_I_ij(S,i,j)-3.87)**2


    return fit_1, fit_2

In [17]:
M, N = 3, 5
individual = [1,1,0,0,1,0,1,0,0,0,1,1,1,1,1]
fit_1, fit2 = evaluate(individual)

[[1 1 0 0 1]
 [0 1 0 0 0]
 [1 1 1 1 1]]
